# .github/filters.yaml

# Shared path filters used by the `changes` job.
#
# Modified files that are not filtered by these exclusions will trigger the `test` jobs in:
# - `.github/workflows/ci-rust.yaml`
#
# The step `Detect file changes based on filters.yaml` uses `dorny/paths-filter` with
# `predicate-quantifier = every`:
# - this is AND semantics
# - it's not possible to re-include a file with a positive pattern
# - exclude only the files to skip, tipically docs and dev config files

# Common exclusions, changes in these files are ignored in all actions.
_common: &common
  - "**" # Must begin with `**`.
  # Markdown.
  - "!**.md"
  # Licenses.
  - "!LICENSE*"
  # Just recipes.
  - "!justfile"
  - "!.just/**"
  # Rust.
  - "!.clippy.toml"
  - "!.rustfmt.toml"
  # Local Docker dev.
  - "!compose.Dockerfile"
  - "!compose.yaml"
  - "!dev.Dockerfile"
  # Local dev.
  - "!.githooks/**"
  - "!.editorconfig"
  - "!.env*"
  - "!.markdownlint.json"
  - "!droast.toml"
  # This file.
  - "!.github/filters.yaml"


# CI: rebuild on any source change.
# Used by .github/workflows/ci-rust.yaml
ci:
  - *common
  - "!tests/**"
