[package]
name = "svgy"
version = "0.6.1"
edition = "2024"
description = "Convert an SVG to optimized icons for all platforms"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ystorian/svgy"
readme = "README.md"
categories = ["development-tools", "command-line-utilities", "multimedia::images"]
keywords = ["svg", "ico", "icon"]
publish = true
include = ["src/**/*.rs", "Cargo.toml", "Cargo.lock", "README.md", "/*.svg", "LICENSE-*"]


[package.metadata.binstall.signing]
algorithm = "minisign"
pubkey = "RWRukfafJ1oiG5PP1IKXRgoI7ntXPbys8WUm9ol6oanMKxEtXdbXisri"

[dependencies]
anyhow = "1"
clap = { version = "4.6", features = ["derive"] }
resvg = { version = "0.48", default-features = false }
oxipng = { version = "10.2", features = ["parallel", "zopfli"], default-features = false }
oxvg_optimiser = { version = "0.0.8", default-features = false }
oxvg_ast = { version = "0.0.8", features = ["roxmltree"] }
oxvg_path = "0.0.8"
quick-xml = "0.42"
svgtypes = "0.16"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
debug = "none"
panic = "abort"


# Profile for GitHub action, used by `.github/workflows/ci-rust.yaml`
[profile.ci]
inherits = "dev"
debug = false
incremental = false
opt-level = 0

[profile.ci.package."*"]
debug = false
incremental = false
opt-level = 0
